### ISSUE TITLE
Support passing credentials via constructor

### ISSUE THREAD

**Issue by pajaydev** [eBay/ebay-oauth-nodejs-client#1]
Right now this library takes the filePath, it would be easy if we can able to pass the credentials through the constructor like below.

```javascript
const ebayAuthToken = new EbayAuthToken({
    "clientId": "---Client Id---",
     "clientSecret": "--- client secret---",
     "devid": "-- dev id ---",
     "redirectUri": "-- redirect uri ---",
})
```

**Comment by andrii33** [comment]
Yeah, that would be a good change. It's required for me to start using the lib. Since I need it for multiple ebay sellers.

**Comment by andrii33** [comment]
You have already implemented it in the correct way here https://github.com/pajaydev/oauth-ebay/blob/master/example.js

**Comment by pajaydev** [comment]
@andrii33 We have moved the same repo under eBay org to make it official.  Moving forward this will be the official one.

**Comment by mattia85** [comment]
> @andrii33 We have moved the same repo under eBay org to make it official. Moving forward this will be the official one.

Really?
